# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('Text', 'Text'), ('Precision', 'Precision'), ('Supplement', 'Supplement'), ('Attention', 'Attention')], default='Text', max_length=30)),
                ('text', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
                ('proposition_initiale', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
                ('nature', models.CharField(choices=[('Exemple', 'Exemple'), ('Donc', 'Donc'), ('Concurrence', 'Concurrence'), ('Syl', 'Syl')], default='Donc', max_length=30)),
                ('trafic', models.IntegerField(default=0)),
                ('junction', models.CharField(max_length=30)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('Reponse', 'Reponse'), ('Demande', 'Demande')], default='Reponse', max_length=30)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
                ('nature', models.CharField(choices=[('Diagnostic', 'Diagnostic'), ('Action', 'Action'), ('Reference', 'Reference')], default='Diagnostic', max_length=30)),
                ('trafic', models.IntegerField(default=0)),
                ('demande_precision', models.BooleanField()),
                ('demande_supplement', models.BooleanField()),
                ('demande_attention', models.BooleanField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Cycle')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Proposition'),
        ),
        migrations.AddField(
            model_name='link',
            name='left_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_left_prop', to='gdpcore.Proposition'),
        ),
        migrations.AddField(
            model_name='link',
            name='right_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_right_prop', to='gdpcore.Proposition'),
        ),
        migrations.AddField(
            model_name='link',
            name='second_left_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_second_left_prop', to='gdpcore.Proposition'),
        ),
        migrations.AddField(
            model_name='comment',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Proposition'),
        ),
    ]
