# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0005_auto_20160412_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 14, 10, 24, 227133, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
