# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0008_auto_20160418_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 12, 4, 1, 324114, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='nature',
            field=models.CharField(choices=[('Text', 'Text'), ('Precision', 'Precision'), ('Supplement', 'Supplement'), ('Attention', 'Attention'), ('MP', 'Modification de proposition'), ('CA', "Changement d'avis"), ('NP', 'Nouvelle proposition'), ('TX', 'Texte'), ('DP', 'Demande de précision'), ('DS', 'Demande de supplément')], default='Text', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='nature',
            field=models.CharField(choices=[('Reponse', 'Reponse'), ('Demande', 'Demande'), ("Demande d'attention", "Demande d'attention"), ('Demande de précision', 'Demande de précision'), ('Demande de source', 'Demande de source'), ('NL', 'Nouveau lien'), ('MP', 'Modification de proposition'), ('CA', "Changement d'avis"), ('SP', 'Suppression de proposition'), ('CL', 'Critique de lien'), ('NC', 'Nouveau commentaire'), ('DA', "Demande d'attention"), ('DP', 'Demande de précision'), ('DS', 'Demande de source')], default='Reponse', max_length=30),
        ),
    ]
