# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0009_auto_20160419_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='tags',
            field=models.CharField(default='default', max_length=3000),
            preserve_default=False,
        ),
    ]
