# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0010_proposition_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='simil',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
