# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0011_proposition_simil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='last_prop_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 9, 49, 47, 807916, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='nb',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='simil',
            field=models.FloatField(default=0),
        ),
    ]
