# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0012_auto_20160422_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Pending')], default='A', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='nature',
            field=models.CharField(choices=[('Reponse', 'Reponse'), ('Demande', 'Demande'), ("Demande d'attention", "Demande d'attention"), ('Demande de précision', 'Demande de précision'), ('Demande de source', 'Demande de source'), ('NL', 'Nouveau lien'), ('MP', 'Modification de proposition'), ('CA', "Changement d'avis"), ('SP', 'Suppression de proposition'), ('CL', 'Critique de lien'), ('NC', 'Nouveau commentaire'), ('DA', "Demande d'attention"), ('DP', 'Demande de précision'), ('DS', 'Demande de source'), ('DV', 'Demande de validation de lien')], default='Reponse', max_length=30),
        ),
    ]
