# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0014_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemgraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('displayed', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='graph',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='elemgraph',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Graph'),
        ),
        migrations.AddField(
            model_name='elemgraph',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Proposition'),
        ),
    ]
