# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='originx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graph',
            name='originy',
            field=models.IntegerField(default=0),
        ),
    ]
