# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0017_auto_20160517_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('sens', models.BooleanField()),
                ('inverse', models.CharField(max_length=100)),
                ('logic', models.CharField(max_length=100)),
                ('strokeColor', models.CharField(max_length=100)),
                ('strokeWidth', models.IntegerField()),
                ('source', models.BooleanField()),
                ('target', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='graph',
            name='graphstring',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='link',
            name='junction',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='link',
            name='nature',
            field=models.CharField(choices=[('Exemple', 'Exemple'), ('Donc', 'Donc'), ('Concurrence', 'Concurrence'), ('Syl', 'Syl'), ('E', 'Exemple'), ('D', 'Donc'), ('C', 'Concurrence')], default='Donc', max_length=30),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='demande_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='demande_precision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='demande_supplement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='tags',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
