# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0019_link_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktype',
            name='source',
        ),
        migrations.RemoveField(
            model_name='linktype',
            name='target',
        ),
        migrations.AddField(
            model_name='linktype',
            name='arrows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
