# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0020_auto_20160525_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktype',
            name='texte',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
