# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0021_linktype_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='videoBeginning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposition',
            name='videoEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposition',
            name='ytid',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposition',
            name='nature',
            field=models.CharField(choices=[('Diagnostic', 'Diagnostic'), ('Action', 'Action'), ('Reference', 'Reference'), ('YT', 'Youtube')], default='Diagnostic', max_length=30),
        ),
    ]
