# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0022_auto_20160526_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktype',
            name='texte',
        ),
        migrations.AddField(
            model_name='linktype',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='ytid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
