# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polikif', '0002_selection_proposition'),
        ('gdpcore', '0024_auto_20160609_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='parti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polikif.Parti'),
            preserve_default=False,
        ),
    ]
