# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0025_graph_parti'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='propNumber',
            field=models.IntegerField(default=0),
        ),
    ]
