# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0027_historicalgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentgraph',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.CommentGraph'),
        ),
        migrations.AddField(
            model_name='commentgraph',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Link'),
        ),
        migrations.AddField(
            model_name='commentgraph',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Proposition'),
        ),
    ]
