# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0028_auto_20160613_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentgraph',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
