# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdpcore', '0029_commentgraph_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShowPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.CharField(max_length=3000)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=3)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Link')),
                ('proposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Proposition')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Show')),
            ],
        ),
    ]
