# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0031_auto_20160617_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpart',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audioex'),
        ),
    ]
