# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0032_showpart_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showpart',
            name='text',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
