# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0035_auto_20161005_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Cycle'),
        ),
        migrations.AlterField(
            model_name='link',
            name='nature',
            field=models.CharField(choices=[('Exemple', 'Exemple'), ('Donc', 'Donc'), ('Concurrence', 'Concurrence'), ('Syl', 'Syl'), ('E', 'Exemple'), ('D', 'Donc'), ('C', 'Concurrence'), ('P', 'Précision'), ('Cep', 'Cependant')], default='Donc', max_length=30),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
