# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0036_auto_20161005_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpart',
            name='theme',
            field=models.CharField(default='default', max_length=1000),
        ),
        migrations.AddField(
            model_name='showpart',
            name='themeOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showpart',
            name='themePrefix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
