# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0037_auto_20161010_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpart',
            name='synthese',
            field=models.IntegerField(default=0),
        ),
    ]
