# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
    ]
