# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0002_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default='default', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
