# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0003_photo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record',
            field=models.FileField(default='default', upload_to='records'),
            preserve_default=False,
        ),
    ]
