# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0031_auto_20160617_1206'),
        ('univok', '0004_record_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='proposition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Proposition'),
            preserve_default=False,
        ),
    ]
