# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0031_auto_20160617_1206'),
        ('univok', '0009_event_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Show')),
            ],
        ),
    ]
