# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0010_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
