# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0011_auto_20160910_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='picture',
            field=models.ImageField(default=1, upload_to='speakers'),
            preserve_default=False,
        ),
    ]
