# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('univok', '0012_speaker_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
