# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpcore', '0034_auto_20160923_1310'),
        ('univok', '0013_speaker_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='show',
        ),
        migrations.AddField(
            model_name='question',
            name='showpart',
            field=models.ManyToManyField(to='gdpcore.ShowPart'),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
