# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0014_auto_20160926_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='displayanimation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='displaydescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='displayfacilitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='displayintervenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='displayphoto',
            field=models.BooleanField(default=False),
        ),
    ]
