# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0015_auto_20160928_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(max_length=10000)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univok.Event')),
            ],
        ),
    ]
