# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0017_auto_20161005_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='proposition',
            field=models.ManyToManyField(blank=True, null=True, to='gdpcore.Proposition'),
        ),
    ]
