# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0019_auto_20161005_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='displayinscription',
            field=models.BooleanField(default=False),
        ),
    ]
