# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0021_event_inscriptionurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='univok.Event'),
        ),
    ]
