# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0022_question_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 13, 0, 25, 58, 543724, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
