# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0023_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='status',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
