# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univok', '0025_auto_20161026_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='default', max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdpcore.Graph'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='default', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, null=True, to='univok.Speaker'),
        ),
    ]
