# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion_cellule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DC', 'Directeur Cellule'), ('M', 'Membre')], default='M', max_length=30)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Pending')], default='A', max_length=30)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion_parti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PP', 'Président parti'), ('DTK', 'Directeur Think Tank'), ('M', 'Membre')], default='M', max_length=30)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Pending')], default='A', max_length=30)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Parti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('O', 'Officielle'), ('A', 'Acceptée'), ('R', 'Rejetée')], default='M', max_length=30)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Pending')], default='A', max_length=30)),
                ('creation_date', models.DateTimeField()),
                ('parti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polikif.Parti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cellule',
            name='parti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polikif.Parti'),
        ),
        migrations.AddField(
            model_name='adhesion_parti',
            name='parti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polikif.Parti'),
        ),
        migrations.AddField(
            model_name='adhesion_parti',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adhesion_cellule',
            name='cellule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polikif.Cellule'),
        ),
        migrations.AddField(
            model_name='adhesion_cellule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
