# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmeetup', models.IntegerField()),
                ('name', models.CharField(default='default', max_length=1000)),
                ('status', models.CharField(default='default', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmeetup', models.IntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=1234399306000)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmeetup', models.IntegerField()),
                ('name', models.CharField(default='default', max_length=1000)),
                ('adress', models.CharField(default='default', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdn.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdn.Member')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organisator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdn.Member'),
        ),
    ]
