# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-01 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 1, 16, 39, 19, 548536, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(max_length=1000),
        ),
    ]
