# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_auto_20161001_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='presenceCount',
            field=models.IntegerField(default=0),
        ),
    ]
