# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0003_member_presencecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
