# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0005_presence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organisationCount',
            field=models.IntegerField(default=0),
        ),
    ]
