# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-08 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0006_member_organisationcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cdn.Place'),
            preserve_default=False,
        ),
    ]
